---
title: "Reproducible research course project 2"
author: "by RAKESH JOSE"
date: "7/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#* WEATHER EVENTS ON PUBLIC HEALTH AND ECONOMY IN THE UNITED STATES OF AMERICA*

##*SYNOPSIS*


"In this report , an analysis about the impact of Storms and other severe weather events are done. These events  causes both public health and economic problems for communities and municipalities. Many severe events can result in fatalities, injuries, and property damage, and preventing such outcomes to the extent possible is a key concern."

 "This project involves exploring the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage."
 
  ##* BASIC BACKROUND SETTINGS*
  
    getwd()
    
library(knitr)
library(stats)
library(plyr)
library(markdown)
library(dplyr)

storm <- read.csv(file = "repdata_data_StormData.csv", header = TRUE, sep = ",")
dim(storm)

"There are 902297 rows and 37 columns in total. The  various events in the database started in the year 1950 and end's in November 2011. Only fewer events are recorded in the databases of the earlier years.The databases of more recent years has to be considered for completing the analysis."

names(storm)

str(storm)


## *WRANGLING OF THE DATA*

"Defining the various set of variables that is available from the data set"

"-EVTYPE: Event Type (Tornados, Flood, ….)"

 "- FATALITIES: Number of Fatalities"
 
 "- INJURIES: Number of Injuries"
 
 "- PROPDMG: Property Damage"
 
 "- PROPDMGEXP: Units for Property Damage (magnitudes - K,B,M)"
 
 "- CROPDMG: Crop Damage"
 
 "- CROPDMGEXP: Units for Crop Damage (magnitudes - K,BM,B)"
 
 variablesNedeed <- c("EVTYPE", "FATALITIES", "INJURIES", "PROPDMG", "PROPDMGEXP", "CROPDMG", "CROPDMGEXP")
 
 storm <- storm[variablesNedeed]
 
 dim(storm)
 
 names(storm)
 
 str(storm)
 
 ## *PROPERTY DAMAGE DUE TO WEATHER EVENTS*
 
 unique(storm$PROPDMGEXP)
 library(plyr)
 
 storm$PROPDMGEXP <- mapvalues(storm$PROPDMGEXP, from = c("K", "M","", "B", "m", "+", "0", "5", "6", "?", "4", "2", "3", "h", "7", "H", "-", "1", "8"), to = c(10^3, 10^6, 1, 10^9, 10^6, 0, 1, 10^5, 10^6, 0, 10^4, 10^2, 10^3, 10^2, 10^7, 10^2, 0, 10, 10^8))
 
 storm$PROPDMGEXP <- as.numeric(as.character(storm$PROPDMGEXP))
 storm$PROPDMGTOTAL <- (storm$PROPDMG * storm$PROPDMGEXP)/1000000000
 
 unique(storm$CROPDMGEXP)
 
 storm$CROPDMGEXP <- mapvalues(storm$CROPDMGEXP, from = c("","M", "K", "m", "B", "?", "0", "k","2"), to = c(1, 10^6, 10^3, 10^6, 10^9, 0, 1, 10^3, 10^2))
 
 storm$CROPDMGEXP <- as.numeric(as.character(storm$CROPDMGEXP))
 storm$CROPDMGTOTAL <- (storm$CROPDMG * storm$CROPDMGEXP)/1000000000
 
  ## *ANALYSIS ABOUT THE IMPACT OF STORMS AND OTHER SEVERE WEATHER EVENTS*
  
"The analysis of the weather events is done from the  U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database."

### * WEATHER EVENTS THAT ARE HARMFUL TO HUMANS*

"To determine the type of weather events which are  most harmful to the humans we must look at the variable dataset counts of  fatalities and Injuries occurred from the given dataset."

sumFatalities <- aggregate(FATALITIES ~ EVTYPE, data = storm,  FUN="sum")

dim(sumFatalities)

"Ranking the Number of Fatalities in an order to determine the top 10 severe weather events."


fatalitieratesinevents <- sumFatalities[order(-sumFatalities$FATALITIES), ][1:10, ]
dim(fatalitieratesinevents)

fatalitieratesinevents


### *A Bar Plot detailing the  Fatalities rates in severe weather events.*

par(mfrow = c(1,1), mar = c(12, 4, 3, 2), mgp = c(3, 1, 0), cex = 0.8)
barplot(fatalitieratesinevents$FATALITIES, names.arg = fatalitieratesinevents$EVTYPE, las = 3, main = "Fatalities in severe weather events", ylab = "Number of Fatalities")

dev.copy(png, "fatalities in severe weather events.png", width = 480, height = 480)

dev.off()

sumInjuries <- aggregate(INJURIES ~ EVTYPE, data = storm,  FUN="sum")
dim(sumInjuries)

"Ranking the Number of injuries in an order to determine the top 10 severe weather events."

injurieratesinevents <- sumInjuries[order(-sumInjuries$INJURIES), ][1:10, ]
dim(injurieratesinevents)

injurieratesinevents

### *A Bar Plot detailing the  Injuries rates in severe weather events.*

par(mfrow = c(1,1), mar = c(12, 6, 3, 2), mgp = c(4, 1, 0), cex = 0.8)
barplot(injurieratesinevents$INJURIES, names.arg = injurieratesinevents$EVTYPE, las = 3, main = "Injuries in severe weather events", ylab = "Number of Injuries")

dev.copy(png, "injuries in severe weather events.png", width = 480, height = 480)

dev.off()


### * IMPACT OF SEVERE WEATHER EVENTS ON ECONOMY*

"To determine the impact on economy due to the severe weather events w we must look at the variable dataset counts of property damages and crop damages occurred from the given dataset."

sumPropertyDamage <- aggregate(PROPDMGTOTAL ~ EVTYPE, data = storm,  FUN="sum")
dim(sumPropertyDamage)

"Ranking the amounts of property damages in an order to determine the effect on economy in top 10 severe weather events."

propertydamagesinevents <- sumPropertyDamage[order(-sumPropertyDamage$PROPDMGTOTAL), ][1:10, ]
propertydamagesinevents

### *A Bar Plot detailing the property damage rates in severe weather events.*

par(mfrow = c(1,1), mar = c(12, 6, 3, 2), mgp = c(3, 1, 0), cex = 0.8)
barplot(propertydamagesinevents$PROPDMGTOTAL, names.arg = propertydamagesinevents$EVTYPE, las = 3, main = "Property Damages in severe weather Events", ylab = "Damage Property Values (in Billions)")

dev.copy(png, "property damages in weather events.png", width = 480, height = 480)
dev.off()

sumCropDamage <- aggregate(CROPDMGTOTAL ~ EVTYPE, data = storm,  FUN="sum")
dim(sumCropDamage)

"Ranking the amounts of crop damages in an order to determine the effect on economy in top 10 severe weather events."

cropdamagesinevents <- sumCropDamage[order(-sumCropDamage$CROPDMGTOTAL), ][1:10, ]
cropdamagesinevents

### *A Bar Plot detailing the crop damage rates in severe weather events.*

par(mfrow = c(1,1), mar = c(12, 6, 3, 2), mgp = c(3, 1, 0), cex = 0.8)
barplot(cropdamagesinevents$CROPDMGTOTAL, names.arg = cropdamagesinevents$EVTYPE, las = 2, main = "Crop Damages in severe weather Events", ylab = "Damage Crop Values (in Billions) ")

dev.copy(png, "crop damages in weather events.png", width = 480, height = 480)
dev.off()


## *RESULTS*

" 1. Across the United States, which types of events are most harmful with respect to population health?"

    "Tornado's causes the highest number of Fatalities and Injuries from the given data set."
    
    
" 2. Across the United States, which types of events have the greatest economic consequences?"
  
    "Floods causes highest  rates in property damages  and droughts causes the highest rate in crop damages."




 